extends RefCounted
var runner
func test_industry_navigation_stays_in_viewport() -> void:
	var modal := CompanyOS.new("home_laptop")
	UIRoot.open_modal(modal)
	await runner.get_tree().process_frame
	await runner.get_tree().process_frame
	runner.check(modal.panel.get_global_rect().position.y>=0 and modal.panel.get_global_rect().end.y<=360,"additional industry launcher cannot push OS outside screen")
	var launcher := modal.find_child("Tab_real_estate",true,false) as Button
	var nav: Node=launcher.get_parent()
	runner.check(nav.get_parent() is ScrollContainer,"all industry navigation has its own scroll")
	(nav.get_parent() as ScrollContainer).ensure_control_visible(launcher)
	await runner.get_tree().process_frame
	var rect := launcher.get_global_rect()
	runner.check(rect.position.y>=0 and rect.end.y<=360,"last launcher becomes actually clickable")
	modal.close()
	await runner.get_tree().process_frame
func setup(extra := 0.0) -> String:
	Company.register("Realty Test","real_estate","Harlow")
	Company.open_business_account(25000)
	if extra>0:Ledger.post(GameState.company_id(),"QA property equity",[{"acct":"cash","dr":extra},{"acct":"equity","cr":extra}])
	runner.check(Compliance.apply_permit("brokerage")["ok"],"paid exam application")
	runner.check(not RealEstate.licence(),"three-day processing")
	Clock.advance(3*Clock.DAY)
	runner.check(RealEstate.licence(),"licence granted")
	runner.check(Living.lease("realty_office")["ok"],"real brokerage lease")
	runner.check(RealEstate.start()["ok"],"brokerage opens")
	return GameState.company_id()
func test_open_gates_permit_and_world_data() -> void:
	runner.check(not RealEstate.start()["ok"],"no-company gate")
	setup()
	runner.eq(RealEstate.listings().size(),9,"six apartments and three rowhouses")
	runner.eq(DataDB.district_def_in_city("residential")["status"],"active","map open")
	runner.check(DataDB.districts["residential"]["exits"].any(func(e):return e["to"]=="old_town"),"walkable Old Town link")
	runner.check(not Compliance.apply_permit("brokerage")["ok"],"no repeated application")
	runner.check(not Compliance.apply_permit("building")["ok"],"developer growth gate")
	runner.check(Industries.tabs().any(func(t):return t["id"]=="real_estate"),"registered OS tab")
	runner.check(Ledger.check_balanced(),"opening balanced")
func test_actual_match_viewing_and_traceable_commission() -> void:
	var entity := setup()
	var mandate: Dictionary=RealEstate.S()["mandates"].values()[0]
	var client: Dictionary=RealEstate.S()["clients"].values()[0]
	client.merge({"kind":mandate["kind"],"rooms":mandate["rooms"],"budget":float(mandate["floor"])*1.1,"urgency":5},true)
	runner.eq(RealEstate.score(mandate,client),1.0,"exact match")
	var closed := false
	for attempt in 40:
		client["status"]="open"
		var time := Clock.now()
		var result := RealEstate.viewing(mandate["id"],client["id"],"soft")
		runner.eq(Clock.now()-time,int(RealEstate.cfg()["show_minutes"]),"viewing takes actual game time")
		if result.get("closed",false):
			closed=true
			runner.eq(Jobs.get_job(result["job"])["status"],"paid","commission invoice collected")
			runner.check(not RealEstate.viewing(mandate["id"],client["id"],"soft")["ok"],"deal cannot pay twice")
			break
	runner.check(closed,"observed successful deal")
	runner.check(-Ledger.balance(entity,"revenue")>0,"revenue came from a real matched contract")
	runner.check(Ledger.check_balanced(),"viewing and commission balanced")
func test_mortgage_amortization_interest_and_market_equity() -> void:
	var entity := setup(90000)
	runner.check(not RealEstate.buy("maple_1",.1,25)["ok"],"down payment bounds")
	runner.check(not RealEstate.buy("maple_1",.2,10)["ok"],"term bounds")
	runner.check(not RealEstate.buy("maple_1",NAN,25)["ok"],"finite terms")
	var purchase := RealEstate.buy("maple_1",.2,25)
	runner.check(purchase["ok"],"mortgage purchase")
	var loan: Dictionary=purchase["loan"]
	var balance := float(loan["balance"])
	var expected := Bank.monthly_payment(balance,300,float(loan["apr"]))
	var interest := snappedf(balance*float(loan["apr"])/12,.01)
	Bank._payment(loan)
	runner.check(absf(float(loan["balance"])-(balance-expected+interest))<.011,"principal amortizes exact cents")
	var book := float(RealEstate.S()["properties"]["maple_1"]["book"])
	RealEstateMarket.S()["index"]=1.1
	runner.eq(RealEstateMarket.value(RealEstate.S()["properties"]["maple_1"]),198000.0,"market mark independent")
	runner.eq(RealEstate.S()["properties"]["maple_1"]["book"],book,"unrealized value creates no cash or book income")
	runner.check(float(Bank.lending_basis()["max"])>0,"mortgage debt not deducted from net equity twice")
	var rate := float(loan["apr"])
	RealEstate.crisis("rate")
	Bank._payment(loan)
	runner.check(float(loan["apr"])>rate,"base-linked mortgage reprices")
	runner.check(Ledger.balance(entity,"exp:interest")>0,"interest expense actual")
	runner.check(Ledger.check_balanced(),"mortgage balanced")
func test_vacancy_pricing_screening_tenant_arrears_and_repair() -> void:
	var entity := setup(90000)
	RealEstate.buy("maple_1",.2,25)
	runner.check(RealEstate.vacancy_days(1.4,750)>RealEstate.vacancy_days(1,450),"high asking rent and strict screening extend vacancy")
	var result := RealEstate.list_rental("maple_1",1,450)
	runner.check(result["ok"],"listed owned unit")
	Clock.advance(int(result["days"])*Clock.DAY)
	var property: Dictionary=RealEstate.S()["properties"]["maple_1"]
	runner.eq(property["status"],"occupied","actual generated tenant")
	runner.check(property["tenant"]["credit"]>=450,"screening respected")
	runner.check(not RealEstate.list_rental("maple_1",1,450)["ok"],"cannot overwrite occupied tenancy")
	var event := EventEngine.trigger("real_estate_arrears")
	runner.check(EventEngine.choose(event["iid"],"respond")["ok"],"actual tenant crisis effect")
	RealEstate.handle("re.rent",{"id":"maple_1"})
	runner.check(Ledger.balance(entity,"accounts_receivable")>0,"missed rent stays receivable")
	Clock.advance(30*Clock.DAY)
	runner.check(Ledger.check_balanced(),"tenant payment, arrears, damage and monthly charges balance")
func test_renovation_completion_budget_and_save_load() -> void:
	setup(120000)
	RealEstate.buy("maple_1",.2,25)
	runner.check(RealEstate.renovate("maple_1","modern")["ok"],"modern refurbishment")
	runner.check(not RealEstate.list_rental("maple_1",1,500)["ok"],"cannot rent unfinished unit")
	runner.check(SaveSystem.save(96),"save mortgage and work")
	GameState.data.erase("real_estate")
	runner.check(SaveSystem.load_data(96),"load actual save")
	Clock.advance(20*Clock.DAY)
	var property: Dictionary=RealEstate.S()["properties"]["maple_1"]
	runner.eq(property["uplift"],.18,"completed refurbishment boosts market and rent")
	runner.check(property["renovation"].is_empty(),"work cleared")
	runner.check(Ledger.check_balanced(),"renovation and possible overrun balanced")
func test_ruiz_milestones_delay_completion_map_and_sales() -> void:
	var entity := setup(2500000)
	RealEstate.buy("maple_1",.2,25)
	Compliance.apply_permit("building")
	Clock.advance(7*Clock.DAY)
	var result := RealEstate.develop("small","TEST TOWER")
	runner.check(result["ok"],"permitted development")
	runner.eq(Jobs.get_job(result["job"])["direction"],"purchase","outbound contractor contract")
	runner.eq(-Ledger.balance(entity,"revenue"),0.0,"paying Ruiz never creates revenue")
	runner.eq(RealEstate.lot_definition(DataDB.buildings["lot7"])["exterior"]["fallback"],"warehouse_shed","construction visible")
	var due := int(RealEstate.S()["project"]["due"])
	RealEstate.crisis("delay")
	runner.check(int(RealEstate.S()["project"]["due"])>due,"contractor delay real")
	Clock.advance_to(int(RealEstate.S()["project"]["due"])+Clock.DAY)
	runner.eq(RealEstate.S()["project"]["status"],"completed","paid milestones complete")
	runner.eq(RealEstate.S()["properties"].size(),7,"six saleable completed units")
	runner.eq(RealEstate.lot_definition(DataDB.buildings["lot7"])["name"],"TEST TOWER","world/map name saved")
	runner.eq(RealEstate.lot_definition(DataDB.buildings["lot7"])["exterior"]["fallback"],"apartment_mid","completed building visible")
	var map := CityMapModal.new(false)
	UIRoot.open_modal(map)
	runner.check(map.find_child("Landmark_lot7",true,false)!=null,"completed project is an actual city-map marker")
	map.close()
	runner.check(RealEstate.list_building(1,450)["ok"],"whole-building rental action")
	runner.eq(Sim.pending("re.tenant").filter(func(p):return str(p["p"]["id"]).begins_with("tower_")).size(),6,"each unit retains its own tenant schedule")
	runner.check(RealEstate.sell("tower_1")["ok"],"sell completed unit")
	runner.check(not RealEstate.sell("tower_1")["ok"],"cannot sell twice")
	runner.check(Ledger.check_balanced(),"construction and unit sale balanced")
	Insolvency.close_company()
	runner.eq(RealEstate.lot_definition(DataDB.buildings["lot7"])["name"],"TEST TOWER","city landmark survives company closure")
	runner.check(Ledger.check_balanced(),"profitable distribution above initial investment balances")

func test_overrun_after_milestones_requires_extra_payment() -> void:
	var entity := setup(2500000)
	RealEstate.buy("maple_1",.2,25)
	Compliance.apply_permit("building")
	Clock.advance(7*Clock.DAY)
	RealEstate.develop("small","LATE COST")
	Clock.advance(31*Clock.DAY)
	var project: Dictionary=RealEstate.S()["project"]
	var paid := float(project["paid"])
	RealEstate.crisis("delay")
	var job := Jobs.get_job(project["job"])
	runner.check(not Jobs.invoice(project["job"])["ok"],"outbound job cannot invoice fictitious revenue")
	runner.eq(float(Bank.lending_basis()["contracts"]),0.0,"outbound engineering obligation is not a receivable")
	Clock.advance_to(int(project["due"])+Clock.DAY)
	runner.eq(project["status"],"completed","extra cost settled before handover")
	runner.check(float(project["paid"])>paid,"late overrun actually paid")
	runner.eq(job["paid_cost"],project["budget"],"all revised contractor costs covered")
	runner.eq(Ledger.balance(entity,"construction_in_progress"),0.0,"completion transfers every cost")
	runner.check(Ledger.check_balanced(),"late extra costs balance")
func test_closure_cancels_tenants_work_mortgages_and_persists_city_landmark() -> void:
	var entity := setup(90000)
	RealEstate.buy("maple_1",.2,25)
	RealEstate.list_rental("maple_1",1,500)
	RealEstate.renovate("maple_1","basic")
	var close := Insolvency.close_company()
	runner.check(close["ok"],"core close")
	runner.check(not RealEstate.is_running(),"industry closed")
	runner.eq(Ledger.balance(entity,"property_assets"),0.0,"property book liquidated")
	runner.eq(Sim.pending("re.tenant").size(),0,"tenant arrival cancelled")
	Clock.advance(40*Clock.DAY)
	runner.eq(Ledger.balance(entity,"accounts_receivable"),0.0,"no post-close rents")
	runner.check(Ledger.check_balanced(),"auction, debt settlement and closure balanced")
func test_old_save_lazy_state_and_segment_totals() -> void:
	GameState.data.erase("real_estate")
	runner.check(not RealEstate.is_running(),"old save initializes without operation")
	var entity := setup(90000)
	RealEstate.buy("maple_2",.25,30)
	RealEstate.list_rental("maple_2",.9,450)
	Clock.advance(45*Clock.DAY)
	var report := Segments.compute(entity,0,Clock.now()+1)
	var company := MonthClose.compute(entity,0,Clock.now()+1)
	runner.check(absf(float(report["totals"]["operating_profit"])-float(company["business_profit"]))<.011,"segments equal company profit")
	runner.check(Ledger.check_balanced(),"old-save full cycle balanced")
