extends Node
## Global signal hub. Systems emit, presentation listens.

signal notify(text: String, kind: String, icon: String)
signal cash_changed(entity: String, delta: float)
signal ledger_posted(entry: Dictionary)
signal order_placed(order_id: String)
signal order_packed(order_id: String)
signal order_shipped(order_id: String)
signal order_delivered(order_id: String)
signal return_requested(order_id: String)
signal review_posted(order_id: String, stars: int)
signal po_placed(po_id: String)
signal po_arrived(po_id: String)
signal listing_changed(listing_id: String)
signal flag_set(flag_name: String)
signal location_entered(kind: String, id: String)
signal interacted(action: String, id: String)
signal decision_requested(instance: Dictionary)
signal message_received(from_id: String, text: String)
signal objective_changed()
signal progress_moment(text: String, receipt: String)
signal chapter_completed(chapter_id: String)
signal month_closed(report: Dictionary)
signal company_registered(entity_id: String)
signal contract_changed(contract_id: String)
signal state_loaded()
signal world_refresh()
signal dialogue_finished(conversation_id: String)
signal solvency_warning(entity: String)
