extends Node
## Music and sound effects. Music follows the scene (menu, district day/night, café, office, home) with
## a crossfade; effects answer UI and game events (button clicks, modals, money in and out, messages,
## objectives, doors). Volumes live in user://settings.cfg (Music / SFX buses). Assets are
## generated by tools/media/make_game_audio.py until licensed audio replaces them.

const SETTINGS := "user://settings.cfg"
const SFX := ["click", "open", "close", "notify", "cash", "spend", "success", "fanfare", "error", "phone", "door", "page"]

var music_volume := 0.8
var sfx_volume := 0.8
var _a: AudioStreamPlayer
var _b: AudioStreamPlayer
var _current := ""
var _pool: Array[AudioStreamPlayer] = []
var _cache := {}
var _last := {}
var _headless := false
var _audio_unlocked := not OS.has_feature("web")
var _pending_music := ""


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_headless = DisplayServer.get_name() == "headless"   # tests and servers: stay silent
	_ensure_bus("Music")
	_ensure_bus("SFX")
	var cfg := ConfigFile.new()
	if cfg.load(SETTINGS) == OK:
		music_volume = float(cfg.get_value("audio", "music", music_volume))
		sfx_volume = float(cfg.get_value("audio", "sfx", sfx_volume))
	_apply_volumes()
	_a = _player("Music")
	_b = _player("Music")
	for i in 6:
		_pool.append(_player("SFX"))
	get_tree().node_added.connect(_on_node_added)
	EventBus.notify.connect(_on_notify)
	EventBus.cash_changed.connect(_on_cash)
	EventBus.message_received.connect(func(_f, _t): play("phone", -4.0))
	EventBus.chapter_completed.connect(func(_c): play("fanfare"))
	EventBus.location_entered.connect(func(kind, _id): if kind == "interior": play("door", -6.0))


func _ensure_bus(n: String) -> void:
	if AudioServer.get_bus_index(n) < 0:
		AudioServer.add_bus()
		AudioServer.set_bus_name(AudioServer.bus_count - 1, n)
		AudioServer.set_bus_send(AudioServer.bus_count - 1, "Master")


func _player(bus: String) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = bus
	# Web sample playback can disconnect dynamically created buses; stream uses the mixed output.
	if OS.has_feature("web"):
		p.playback_type = AudioServer.PLAYBACK_TYPE_STREAM
	add_child(p)
	return p


func _apply_volumes() -> void:
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Music"), linear_to_db(maxf(0.0001, music_volume)))
	AudioServer.set_bus_mute(AudioServer.get_bus_index("Music"), music_volume <= 0.001)
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("SFX"), linear_to_db(maxf(0.0001, sfx_volume)))
	AudioServer.set_bus_mute(AudioServer.get_bus_index("SFX"), sfx_volume <= 0.001)


func set_volumes(music: float, sfx: float) -> void:
	music_volume = clampf(music, 0.0, 1.0)
	sfx_volume = clampf(sfx, 0.0, 1.0)
	_apply_volumes()
	var cfg := ConfigFile.new()
	cfg.load(SETTINGS)
	cfg.set_value("audio", "music", music_volume)
	cfg.set_value("audio", "sfx", sfx_volume)
	cfg.save(SETTINGS)


func _stream(path: String) -> AudioStream:
	if not _cache.has(path):
		if not ResourceLoader.exists(path):
			return null
		_cache[path] = load(path)
	return _cache[path]


## One-shot effect. Rate-limited per name so bursts (ten toasts at once) don't stack up.
func play(name: String, db := 0.0) -> void:
	if _headless or not _audio_unlocked:
		return
	var now := Time.get_ticks_msec()
	if now - int(_last.get(name, -1000)) < 70:
		return
	_last[name] = now
	var s := _stream("res://assets/audio/sfx/%s.ogg" % name)
	if s == null:
		return
	for p in _pool:
		if not p.playing:
			p.stream = s
			p.volume_db = db
			p.play()
			return


## Crossfade to a music track ("" = silence).
func music(track: String) -> void:
	if not _audio_unlocked:
		_pending_music = track
		return
	if track == _current or _headless:
		return
	_current = track
	var s: AudioStream = null
	if track != "":
		s = _stream("res://assets/audio/music/%s.ogg" % track)
		if s is AudioStreamOggVorbis:
			(s as AudioStreamOggVorbis).loop = true
	var old := _a
	_a = _b
	_b = old
	var tw := create_tween()
	tw.set_parallel(true)
	if old.playing:
		tw.tween_property(old, "volume_db", -40.0, 1.2)
	if s != null:
		_a.stream = s
		_a.volume_db = -40.0
		_a.play()
		tw.tween_property(_a, "volume_db", -1.0, 1.2)
	tw.chain().tween_callback(func(): if old != _a: old.stop())


## Pick the track for where the player is and what time it is.
func music_for_scene(kind: String, id: String) -> void:
	if kind == "district":
		music("night" if Clock.night_factor() > 0.6 else "day")
		return
	var t := str(DataDB.building(id).get("type", ""))
	match t:
		"cafe":
			music("cafe")
		"home":
			music("night" if Clock.night_factor() > 0.6 else "menu")
		_:
			music("office")


func _process(_d: float) -> void:
	# districts switch between day and night music as the evening comes
	var ws := SceneRouter.world_scene()
	if ws != null and ws.kind == "district" and _current in ["day", "night"]:
		var want := "night" if Clock.night_factor() > 0.6 else "day"
		if want != _current:
			music(want)


func _on_node_added(n: Node) -> void:
	if n is Button:
		(n as Button).pressed.connect(func(): play("click", -8.0))
	elif n is Modal:
		play("open", -8.0)
		(n as Modal).closed.connect(func(): play("close", -10.0))


func _on_notify(_text: String, kind: String, _icon: String) -> void:
	match kind:
		"good":
			play("success", -6.0)
		"bad":
			play("error", -6.0)
		"warn":
			play("error", -10.0)
		"msg":
			pass
		_:
			play("notify", -10.0)


func _on_cash(entity: String, delta: float) -> void:
	if not UIRoot.hud.visible:
		return
	if entity != "player" and entity != GameState.business_entity():
		return
	if delta >= 20.0:
		play("cash", -6.0)
	elif delta <= -20.0:
		play("spend", -10.0)


func _exit_tree() -> void:
	for p in [_a, _b] + _pool:
		if p != null:
			p.stop()
			p.stream = null
	_cache.clear()


func _input(event: InputEvent) -> void:
	if _audio_unlocked:
		return
	if (event is InputEventScreenTouch and event.pressed) or (event is InputEventMouseButton and event.pressed) or (event is InputEventKey and event.pressed):
		_audio_unlocked = true
		music(_pending_music)
