#!/bin/bash
# Encode a Movie Maker capture of the trailer bot into a small, GitHub-previewable MP4 with music.
#   1. record:  godot --path game --rendering-driver opengl3 --resolution 1280x720 \
#                 --write-movie /tmp/tr/f.png --fixed-fps 30 --quit-after 1400 -- --bot=trailer --lang=zh_TW
#               (the bot log prints TRAILER_START frame=N / TRAILER_END frame=M)
#   2. encode:  tools/media/make_trailer.sh /tmp/tr N M docs/media/trailer_zh.mp4
# Music is generated by tools/media/make_music.py (placeholder until a licensed track is chosen).
set -euo pipefail
FRAMES="$1"; START="$2"; END="$3"; OUT="$4"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
N=$((END - START))
SECS=$(python3 -c "print(round($N / 30.0, 3))")
TMP="$(mktemp -d)"
python3 "$ROOT/tools/media/make_music.py" "$TMP/music.wav" "$SECS" >/dev/null
FADE=$(python3 -c "print(max(0.0, $SECS - 1.2))")
mkdir -p "$(dirname "$OUT")"
ffmpeg -y -loglevel error \
  -framerate 30 -start_number "$START" -i "$FRAMES/f%08d.png" \
  -i "$TMP/music.wav" \
  -frames:v "$N" \
  -vf "scale=1280:720:flags=neighbor,format=yuv420p" \
  -c:v libx264 -preset slow -crf 24 -tune animation -movflags +faststart \
  -af "loudnorm=I=-16:TP=-1.5:LRA=11,afade=t=in:d=0.3,afade=t=out:st=$FADE:d=1.2" \
  -c:a aac -b:a 128k -ar 44100 -shortest "$OUT"
rm -rf "$TMP"
echo "$OUT  ${SECS}s  $(du -h "$OUT" | cut -f1)"
