// Atlas slicing and tint normalization only; artwork is generated by imagegen.
const fs = require('fs');
const path = require('path');
const sharp = require(process.env.CITY_SHARP || 'C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root = path.resolve(__dirname, '../..');
const source = path.join(root, 'docs/art_sources/reference_character_20261006');
const output = path.join(root, 'docs/art_sources/custom_character_20261001/components');
const jobs = [];
async function slice(file, columns, rows, names, family, grayscale = false) {
  const input = await sharp(path.join(source,file)).ensureAlpha().raw().toBuffer({resolveWithObject:true});
  const {width,height,channels} = input.info;
  for(let row=0;row<rows.length-1;row++) for(let col=0;col<columns;col++) {
    const l=Math.floor(col*width/columns), r=Math.floor((col+1)*width/columns);
    const t=family==='hair'?[0,260,500][row]:rows[row], b=family==='hair'?[285,560,768][row]:rows[row+1];
    // Generated rows can overlap. Retain the largest connected alpha silhouette
    // inside an overlapping crop, rather than a fragment from the adjacent pose.
    let silhouette=null;
    if(family==='hair') {
      const cw=r-l,ch=b-t,seen=new Uint8Array(cw*ch);let best=[];
      for(let sy=0;sy<ch;sy++)for(let sx=0;sx<cw;sx++) {
        const seed=sy*cw+sx;
        if(seen[seed]||input.data[((sy+t)*width+sx+l)*channels+3]<=24)continue;
        const component=[seed];seen[seed]=1;
        for(let at=0;at<component.length;at++) {
          const p=component[at],px=p%cw,py=Math.floor(p/cw);
          for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++) {
            const nx=px+dx,ny=py+dy,np=ny*cw+nx;
            if(nx<0||ny<0||nx>=cw||ny>=ch||seen[np])continue;
            if(input.data[((ny+t)*width+nx+l)*channels+3]>24){seen[np]=1;component.push(np);}
          }
        }
        if(component.length>best.length)best=component;
      }
      silhouette=new Uint8Array(cw*ch);
      for(const p of best)silhouette[p]=1;
    }
    let x0=r,y0=b,x1=l,y1=t;
    for(let y=t;y<b;y++)for(let x=l;x<r;x++)if(input.data[(y*width+x)*channels+3]>96 && (!silhouette||silhouette[(y-t)*(r-l)+x-l])){
      x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);
    }
    if(x1<=x0)throw new Error(`Missing cell ${file} ${row}/${col}`);
    const crop={left:x0,top:y0,width:x1-x0+1,height:y1-y0+1};
    const raw=await sharp(path.join(source,file)).extract(crop).ensureAlpha().raw().toBuffer({resolveWithObject:true});
    if(silhouette)for(let y=0;y<crop.height;y++)for(let x=0;x<crop.width;x++)
      if(!silhouette[(y+crop.top-t)*(r-l)+x+crop.left-l])raw.data[(y*crop.width+x)*4+3]=0;
    const dye = grayscale || ['business_suit','courier','casual_tee','casual_jacket'].includes(names[col]);
    if(dye)for(let i=0;i<raw.data.length;i+=4){
      const g=Math.min(255,Math.round((raw.data[i]*.2126+raw.data[i+1]*.7152+raw.data[i+2]*.0722)*(family==='clothing'?3:1.08)));
      raw.data[i]=raw.data[i+1]=raw.data[i+2]=g;
    }
    const target=`${family}_${names[col]}_${row}.png`;
    await sharp(raw.data,{raw:raw.info}).png().toFile(path.join(output,target));
    jobs.push({atlas:file,row,col,crop,target,dye,...(silhouette?{alpha_component:'largest',alpha_threshold:24}: {})});
  }
}
async function main(){
  await slice('heads.png',4,[0,520,1024],['round','oval','square','heart'],'head',true);
  await slice('hair.png',8,[0,280,514,768],['messy','short_neat','buzz','side_part','bob','long','ponytail','bun'],'hair',true);
  await slice('clothing.png',9,[0,358,680,1024],['startup_casual','office_professional','home','business_suit','courier','barista','civic_staff','casual_tee','casual_jacket'],'clothing');
  fs.writeFileSync(path.join(source,'crop_manifest.json'),JSON.stringify(jobs,null,2)+'\n');
  console.log(`Integrated ${jobs.length} reference-generated components.`);
}
main().catch(e=>{console.error(e);process.exit(1);});
